name: React vite CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: descargar codigo
        uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar dependecias
        run: npm install
      
      - name: contruir la aplicacion de js
        run: npm run build